# Stage 1: Build the app
FROM node:22.16.0-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code and build it
COPY . .
RUN npm run build

#  Stage 2: Run the app
FROM node:22.16.0-alpine
WORKDIR /app

# Copy only what's needed to run
COPY --from=builder /app/.next .next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json .
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/next.config.js ./

# Expose the port used by Next.js
EXPOSE 3000

# Start Next.js
CMD ["npm", "start"]
