spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} # Default Value: dev (if SPRING_PROFILES_ACTIVE is missing)

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:vaas_id}
    username: ${DB_USER:root}
    password: ${DB_PASS:admin123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
