spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} # Default Value: dev (if SPRING_PROFILES_ACTIVE is missing)

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080